#!/usr/bin/env php
<?php declare(strict_types=1);

use function rikmeijer\Bootstrap\configuration\generate;

foreach ([
             __DIR__ . '/../../autoload.php',
             __DIR__ . '/../vendor/autoload.php',
             __DIR__ . '/vendor/autoload.php'
         ] as $file) {
    if (file_exists($file)) {
        define('BOOTSTRAP_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('BOOTSTRAP_COMPOSER_INSTALL')) {
    fwrite(STDERR, 'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL . '    composer install' . PHP_EOL . PHP_EOL . 'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL);

    die(1);
}

require BOOTSTRAP_COMPOSER_INSTALL;

print 'Generating configuration types...';
generate(__DIR__ . DIRECTORY_SEPARATOR . 'src/bootstrap', 'rikmeijer\Bootstrap', false);
generate(__DIR__ . DIRECTORY_SEPARATOR . 'src/types', 'rikmeijer\Bootstrap\types', false);
print 'Done';